import { getSession } from 'next-auth/client';
import Head from 'next/head';
//Components
// import Login from "../components/Login";
import Header from '../components/Header';
import SideBar from '../components/SideBar';
import Feed from "../components/Feed";
import Widgets from "../components/Widgets";


export default function Home({session}) {

  // if(!session) return <Login/>;

  return (

    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="http://syedkamall.co.uk/wp/wp-content/uploads/2018/05/official-facebook-icon-png-4.png" />
      </Head>

      <Header/>

      <main className="flex">
          <SideBar/>
          <Feed/>
          <Widgets/>
      </main>
    </div>
  )
};

export async function getServerSideProps(context) {
  //getting the user 
  const session = await getSession(context);

  return{
    
    props:{

      session
    }

  }
}
